### ISSUE TITLE
Error when Unpacking and Converting with new .zip file

### ISSUE THREAD

**Issue by prpjzz** [alexpado/hoyoverse-music-unpacker#10]
Error log:
 > Detecting game...
Detected Genshin Impact !
  Audio Files detected: 33
 Unpacking 100% [================================] 33/33 (0:00:19 / 0:00:00) OK
Converting 100% [==============================] 788/788 (0:05:36 / 0:00:00) OK
Extracting 100% [==================================] 1/1 (0:00:50 / 0:00:00) OK
  Patching 100% [================================] 33/33 (0:00:23 / 0:00:00) OK
 Unpacking  ? % [] 0/0 (0:00:00 / ?) OK
Converting  ? % [] 0/0 (0:00:00 / ?) OK
java.lang.UnsupportedOperationException
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149)
        at ovh.akio.hmu.Application.call(Application.java:176)
        at ovh.akio.hmu.Application.call(Application.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at ovh.akio.hmu.Application.main(Application.java:83)

Command i use: C:\Users\Administrator\Downloads\PrismLauncher\runtime\jdk17\bin\java.exe -jar music-unpacker.jar -g="C:\Genshin Impact" -p -d

**Comment by alexpado** [comment]
Update package feature is kinda wanky right now. It should be more stable after my rewrite which should be available after the pre-download of Star Rail.

It will add compatibility with the three games. I'm still working on a local copy of the non-updated Genshin Impact game folder (with the update package)

I'm slow though :(
