### ISSUE TITLE
Wrappers not included in 1.4.0 release

### ISSUE THREAD

**Issue by Cactism** [alexpado/hoyoverse-music-unpacker#20]
Not really sure why this is happening :(

## Input & Output
```
PS C:\Users\Daniel\Downloads> java -jar "C:\Users\Daniel\Downloads\hoyoverse-music-unpacker-1.4.0.jar" --game="C:\miHoYo\Collapse\Appdata\SRGlb" --output="C:\Users\Daniel\Music\HSR" -t 4
Detecting game...
  -- Detected Honkai Star Rail (OS) !
Removing previous files...
Starting unpacking...
ovh.akio.hmu.exceptions.WrapperExecutableNotFound: Unable to access file .\wrappers\quickbms\quickbms.exe
        at ovh.akio.hmu.wrappers.Pck2Wem.<init>(Pck2Wem.java:22)
        at ovh.akio.hmu.GameUnpacker.unpackFiles(GameUnpacker.java:92)
        at ovh.akio.hmu.Application.regularExtract(Application.java:109)
        at ovh.akio.hmu.Application.call(Application.java:92)
        at ovh.akio.hmu.Application.call(Application.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at ovh.akio.hmu.Application.main(Application.java:70)
```

## Machine Info
- Java version: Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
- [DxDiag.txt](https://github.com/user-attachments/files/15921116/DxDiag.txt)

**Comment by alexpado** [comment]
No no, wait, this is actually a valid point. I missed that for the 1.4.0 release, I only provided the JAR and not the ZIP file which includes the external tools

**Comment by alexpado** [comment]
I fixed the release :) Thank you for making me notice it !
